import { useEffect, useMemo, useState, useRef } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  HeartIcon,
  SparklesIcon,
  BoltIcon,
  ShieldCheckIcon,
  ArrowTrendingUpIcon,
  BeakerIcon,
  FireIcon,
  ChartBarSquareIcon,
} from "@heroicons/react/24/outline";
import DashboardLayout from "../../components/DashboardLayout";
import ExplainableChart from "../../components/ExplainableChart";
import RequireAuth from "../../components/RequireAuth";
import RiskCard from "../../components/RiskCard";
import RiskTrendChart from "../../charts/RiskTrendChart";
import { useAuth } from "../../context/AuthContext";
import { clearHealthData, defaultHealthInput, HealthInput, loadInput, loadLatestPrediction, PredictionResult, runPrediction, saveInput, saveLatestPrediction } from "../../services/healthInput";
import { deleteAllTasks, downloadReport, generateExplanation, generateRecommendations, getLatestHealthRecord, cancelAllRequests } from "../../services/api";
import { clearAutoGeneratedGoals, ensureAutoGoalAndTasks } from "../../services/goalAutomation";

type RiskScore = {
  id: string;
  name: string;
  probability: number;
  risk_level: string;
  confidence?: number;
  status?: string;
};

type GroupedScores = {
  metabolic: RiskScore[];
  cardiovascular: RiskScore[];
  other: RiskScore[];
};

const formatPct = (v: number) => `${Math.round(v * 100)}%`;

function buildGoalWorkflowMessage(workflow: {
  action: "create" | "update" | "keep";
  goalTitle: string;
  createdTaskCount: number;
  scheduledDayCount: number;
}) {
  if (workflow.action === "create") {
    return `${workflow.goalTitle} was added to Goals & Progress with ${workflow.createdTaskCount} linked preventive ${workflow.createdTaskCount === 1 ? "task" : "tasks"} across ${workflow.scheduledDayCount} day(s).`;
  }
  if (workflow.action === "update") {
    return `${workflow.goalTitle} was updated in Goals & Progress because the new prediction changed significantly. Existing tasks and progress were kept unchanged.`;
  }
  return `${workflow.goalTitle} stays active in Goals & Progress. The new prediction was close to the previous one, so no duplicate goal or extra tasks were created.`;
}

const iconMap: Record<string, React.ComponentType<React.ComponentProps<"svg">>> = {
  diabetes: SparklesIcon,
  prediabetes: SparklesIcon,
  obesity: FireIcon,
  metabolic_syndrome: SparklesIcon,
  heart_disease: HeartIcon,
  hypertension: BoltIcon,
  stroke_risk: ArrowTrendingUpIcon,
  cardiovascular_risk: ShieldCheckIcon,
  chronic_kidney_disease: BeakerIcon,
  cholesterol_disorder: BeakerIcon,
  lifestyle_risk_index: ChartBarSquareIcon,
};

export default function PredictPage() {
  const router = useRouter();
  const [gender, setGender] = useState<"Male" | "Female" | "Other">("Male");
  const [age, setAge] = useState<number>(40);
  const [bmi, setBmi] = useState<number>(28);
  const [bloodGlucose, setBloodGlucose] = useState<number>(110);
  const [hba1c, setHba1c] = useState<number>(5.8);
  const [bloodPressure, setBloodPressure] = useState<string>("");
  const [smoking, setSmoking] = useState<"never" | "former" | "current">("never");
  const [hypertension, setHypertension] = useState<number>(0);
  const [heartDisease, setHeartDisease] = useState<number>(0);
  const [activityLevel, setActivityLevel] = useState<"low" | "moderate" | "high">("moderate");
  const [sleepHours, setSleepHours] = useState<number>(7);
  const [stressLevel, setStressLevel] = useState<"low" | "moderate" | "high">("moderate");
  const [dietType, setDietType] = useState<"balanced" | "high-carb" | "high-fat" | "low-sugar" | "vegetarian" | "other">("balanced");
  const [predictResult, setPredictResult] = useState<PredictionResult | null>(null);
  const [busy, setBusy] = useState(false);
  const [taskBusy, setTaskBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [latestRecordLoaded, setLatestRecordLoaded] = useState(false);
  const [aiExplanation, setAiExplanation] = useState<string | null>(null);
  const [aiRecommendations, setAiRecommendations] = useState<string | null>(null);
  const [aiBusy, setAiBusy] = useState(false);
  const [lastPredictedInputs, setLastPredictedInputs] = useState<string | null>(null);
  const [taskMessage, setTaskMessage] = useState<string | null>(null);
  const [storageHydrated, setStorageHydrated] = useState(false);
  const isMountedRef = useRef(true);
  const hasSavedPredictionSessionRef = useRef(false);
  const clinicalMetricsRef = useRef<HTMLDivElement | null>(null);
  const bmiInputRef = useRef<HTMLInputElement | null>(null);

  const { userId } = useAuth();
  const storageKey = `predictPageState-${userId || "anonymous"}`;

  useEffect(() => {
    if (!userId) {
      hasSavedPredictionSessionRef.current = false;
      setStorageHydrated(false);
      return;
    }

    try {
      const savedInput = loadInput(userId);
      const savedPrediction = loadLatestPrediction(userId);
      if (!savedInput && !savedPrediction) {
        hasSavedPredictionSessionRef.current = false;
        return;
      }

      hasSavedPredictionSessionRef.current = Boolean(savedInput || savedPrediction);
      const input = savedInput ?? defaultHealthInput;
      setGender(input.gender);
      setAge(input.age);
      setBmi(input.bmi);
      setBloodGlucose(input.blood_glucose_level);
      setHba1c(input.hba1c_level);
      setBloodPressure(input.blood_pressure || "");
      setSmoking(input.smoking_history);
      setHypertension(input.hypertension);
      setHeartDisease(input.heart_disease);
      setActivityLevel(input.activity_level);
      setSleepHours(input.sleep_hours);
      setStressLevel(input.stress_level);
      setDietType(input.diet_type);
      setPredictResult(savedPrediction);
      setLastPredictedInputs(savedInput ? JSON.stringify(savedInput) : null);
      setLatestRecordLoaded(false);
    } catch {
      hasSavedPredictionSessionRef.current = false;
      // ignore invalid saved state
    } finally {
      setStorageHydrated(true);
    }
  }, [storageKey, userId]);

  useEffect(() => {
    if (!predictResult || !lastPredictedInputs) {
      return;
    }

    const currentInputs = JSON.stringify({
      gender,
      age,
      bmi,
      blood_glucose_level: bloodGlucose,
      hba1c_level: hba1c,
      blood_pressure: bloodPressure.trim() || undefined,
      smoking_history: smoking,
      hypertension,
      heart_disease: heartDisease,
      activity_level: activityLevel,
      sleep_hours: sleepHours,
      stress_level: stressLevel,
      diet_type: dietType,
    });

    if (currentInputs !== lastPredictedInputs) {
      setPredictResult(null);
      setAiExplanation(null);
      setAiRecommendations(null);
      setLastPredictedInputs(null);
    }
  }, [predictResult, lastPredictedInputs, gender, age, bmi, bloodGlucose, hba1c, bloodPressure, smoking, hypertension, heartDisease, activityLevel, sleepHours, stressLevel, dietType]);

  const payload = useMemo<HealthInput>(
    () => ({
      gender,
      age,
      bmi,
      blood_glucose_level: bloodGlucose,
      hba1c_level: hba1c,
      blood_pressure: bloodPressure.trim() || undefined,
      smoking_history: smoking,
      hypertension,
      heart_disease: heartDisease,
      activity_level: activityLevel,
      sleep_hours: sleepHours,
      stress_level: stressLevel,
      diet_type: dietType,
    }),
    [gender, age, bmi, bloodGlucose, hba1c, bloodPressure, smoking, hypertension, heartDisease, activityLevel, sleepHours, stressLevel, dietType]
  );

  const groupedScores = useMemo((): GroupedScores => {
    if (!predictResult?.grouped_scores) {
      return { metabolic: [], cardiovascular: [], other: [] };
    }
    return predictResult.grouped_scores;
  }, [predictResult]);

  useEffect(() => {
    if (!userId || !storageHydrated || hasSavedPredictionSessionRef.current) {
      return;
    }

    isMountedRef.current = true;

    async function loadLatest() {
      if (!isMountedRef.current) return;
      try {
        const res = await getLatestHealthRecord();
        if (!isMountedRef.current) return;
        
        const latest = res?.health_record;
        if (!latest) {
          return;
        }

        setGender(latest.gender as "Male" | "Female" | "Other");
        setAge(latest.age);
        setBmi(latest.bmi);
        setBloodGlucose(latest.blood_glucose_level);
        setHba1c(latest.hba1c_level);
        setBloodPressure(latest.blood_pressure || "");
        setSmoking(latest.smoking_history as "never" | "former" | "current");
        setHypertension(latest.hypertension);
        setHeartDisease(latest.heart_disease);
        setActivityLevel(latest.activity_level as "low" | "moderate" | "high");
        setSleepHours(latest.sleep_hours);
        setStressLevel(latest.stress_level as "low" | "moderate" | "high");
        setDietType(latest.diet_type as "balanced" | "high-carb" | "high-fat" | "low-sugar" | "vegetarian" | "other");
        if (isMountedRef.current) {
          setLatestRecordLoaded(true);
        }
      } catch {
        if (isMountedRef.current) {
          setLatestRecordLoaded(false);
        }
      }
    }

    loadLatest();

    return () => {
      isMountedRef.current = false;
      cancelAllRequests();
    };
  }, [userId, storageHydrated]);

  useEffect(() => {
    if (!router.isReady || typeof window === "undefined") {
      return;
    }

    if (window.location.hash !== "#clinical-metrics") {
      return;
    }

    const timer = window.setTimeout(() => {
      clinicalMetricsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
      bmiInputRef.current?.focus();
    }, 120);

    return () => window.clearTimeout(timer);
  }, [router.isReady]);

  return (
    <RequireAuth>
      <DashboardLayout
        title="Prediction"
        subtitle="Predict diabetes and multi-disease risk, view explainability, and generate preventive recommendations."
      >
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-[1.2fr_1.8fr]">
          <div className="rounded-lg border border-slate-800 bg-slate-900 p-6 text-slate-100 min-h-[620px]">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <div className="text-xl font-semibold text-slate-100">User Health Input</div>
                <div className="mt-1 text-base text-slate-300">Enter your clinical and lifestyle details to generate preventive insights.</div>
              </div>
              <div className="rounded-full bg-slate-950 px-4 py-2 text-base text-slate-300">Real-time risk assessment</div>
            </div>

            <div className="mt-6 space-y-6">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <label className="block text-base text-slate-300">
                  <span className="font-medium">Gender</span>
                  <select className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-4 py-3 text-base text-slate-100" value={gender} onChange={(e) => setGender(e.target.value as "Male" | "Female" | "Other")}>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Other">Other</option>
                  </select>
                </label>
                <label className="block text-base text-slate-300">
                  <span className="font-medium">Age</span>
                  <input type="number" min={0} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-4 py-3 text-base text-slate-100" value={age} onChange={(e) => setAge(Number(e.target.value))} />
                </label>
              </div>

              <div ref={clinicalMetricsRef} id="clinical-metrics" className="grid grid-cols-1 gap-4 scroll-mt-24 sm:grid-cols-2">
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">BMI</span>
                  <input ref={bmiInputRef} type="number" min={10} step="0.1" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={bmi} onChange={(e) => setBmi(Number(e.target.value))} />
                </label>
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">Blood Glucose</span>
                  <input type="number" min={50} step="1" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={bloodGlucose} onChange={(e) => setBloodGlucose(Number(e.target.value))} />
                </label>
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">HbA1c</span>
                  <input type="number" min={3} step="0.1" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={hba1c} onChange={(e) => setHba1c(Number(e.target.value))} />
                </label>
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">Blood Pressure</span>
                  <input type="text" placeholder="e.g. 120/80" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={bloodPressure} onChange={(e) => setBloodPressure(e.target.value)} />
                </label>
              </div>

              <div className="rounded-xl border border-cyan-800/40 bg-cyan-950/20 px-4 py-3 text-sm text-cyan-100">
                Update BMI, blood glucose, HbA1c, and blood pressure here. These values will show on your Profile page automatically.
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">Smoking History</span>
                  <select className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={smoking} onChange={(e) => setSmoking(e.target.value as "never" | "former" | "current")}>
                    <option value="never">never</option>
                    <option value="former">former</option>
                    <option value="current">current</option>
                  </select>
                </label>
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">Activity Level</span>
                  <select className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={activityLevel} onChange={(e) => setActivityLevel(e.target.value as "low" | "moderate" | "high")}>
                    <option value="low">low</option>
                    <option value="moderate">moderate</option>
                    <option value="high">high</option>
                  </select>
                </label>
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">Sleep Hours</span>
                  <input type="number" min={0} max={24} step="0.5" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={sleepHours} onChange={(e) => setSleepHours(Number(e.target.value))} />
                </label>
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">Stress Level</span>
                  <select className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={stressLevel} onChange={(e) => setStressLevel(e.target.value as "low" | "moderate" | "high")}> 
                    <option value="low">low</option>
                    <option value="moderate">moderate</option>
                    <option value="high">high</option>
                  </select>
                </label>
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">Diet Type</span>
                  <select className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={dietType} onChange={(e) => setDietType(e.target.value as "balanced" | "high-carb" | "high-fat" | "low-sugar" | "vegetarian" | "other")}> 
                    <option value="balanced">balanced</option>
                    <option value="low-sugar">low-sugar</option>
                    <option value="vegetarian">vegetarian</option>
                    <option value="high-carb">high-carb</option>
                    <option value="high-fat">high-fat</option>
                    <option value="other">other</option>
                  </select>
                </label>
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">Hypertension</span>
                  <select className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={hypertension} onChange={(e) => setHypertension(Number(e.target.value))}>
                    <option value={0}>0</option>
                    <option value={1}>1</option>
                  </select>
                </label>
                <label className="block text-sm text-slate-300">
                  <span className="font-medium">Existing Heart Disease</span>
                  <select className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" value={heartDisease} onChange={(e) => setHeartDisease(Number(e.target.value))}>
                    <option value={0}>0</option>
                    <option value={1}>1</option>
                  </select>
                </label>
              </div>

              {latestRecordLoaded ? (
                <div className="rounded-xl border border-emerald-700/40 bg-emerald-950/20 p-4 text-sm text-emerald-200">
                  Latest saved health record loaded into the form. Adjust values or predict directly.
                </div>
              ) : null}
            </div>

            {error ? <div className="mt-6 rounded border border-red-900/60 bg-red-950/40 p-3 text-sm text-red-200">{error}</div> : null}

            <div className="mt-6 flex flex-col gap-4 sm:flex-row">
              <button
                disabled={busy}
                onClick={async () => {
                  setBusy(true);
                  setError(null);
                  setTaskMessage(null);
                  try {
                    const res = await runPrediction(payload);
                    saveInput(userId, payload);
                    saveLatestPrediction(userId, res);
                    setPredictResult(res);
                    setLastPredictedInputs(JSON.stringify(payload));
                    const workflow = await ensureAutoGoalAndTasks(res);
                    setTaskMessage(buildGoalWorkflowMessage(workflow));
                  } catch (error) {
                    const e = error as { response?: { data?: { detail?: string } }; message?: string };
                    setError(e.response?.data?.detail || e.message || "Prediction failed");
                  } finally {
                    setBusy(false);
                  }
                }}
                className="inline-flex w-full items-center justify-center rounded bg-indigo-500 px-6 py-4 text-base font-semibold text-white transition hover:bg-indigo-600 disabled:opacity-50"
              >
                {busy ? "Predicting..." : "Predict Risks"}
              </button>
              <button
                disabled={!predictResult || taskBusy}
                onClick={async () => {
                  if (!predictResult) return;
                  setTaskBusy(true);
                  setTaskMessage(null);
                  setError(null);
                  try {
                    const workflow = await ensureAutoGoalAndTasks(predictResult);
                    setTaskMessage(buildGoalWorkflowMessage(workflow));
                  } catch (e) {
                    console.error(e);
                    const err = e as { response?: { data?: { detail?: string } }; message?: string };
                    setError(err.response?.data?.detail || err.message || "Failed to create preventive tasks");
                  } finally {
                    setTaskBusy(false);
                  }
                }}
                className="inline-flex w-full items-center justify-center rounded border border-slate-700 bg-slate-950 px-6 py-4 text-base font-semibold text-slate-100 transition hover:border-slate-600 disabled:opacity-50"
              >
                {taskBusy ? "Saving tasks..." : "Create Preventive Tasks"}
              </button>
              <button
                type="button"
                onClick={async () => {
                  setTaskBusy(true);
                  setError(null);
                  setTaskMessage(null);
                  try {
                    await deleteAllTasks();
                    await clearAutoGeneratedGoals();
                    setPredictResult(null);
                    setAiExplanation(null);
                    setAiRecommendations(null);
                    setLastPredictedInputs(null);
                    try {
                      clearHealthData(userId);
                      window.localStorage.removeItem(storageKey);
                    } catch {
                      // ignore
                    }
                  } catch (e) {
                    console.error(e);
                    const err = e as { response?: { data?: { detail?: string } }; message?: string };
                    setError(err.response?.data?.detail || err.message || "Failed to clear prediction and tasks");
                  } finally {
                    setTaskBusy(false);
                  }
                }}
                disabled={taskBusy}
                className="inline-flex w-full items-center justify-center rounded border border-slate-700 bg-slate-900 px-6 py-4 text-base font-semibold text-slate-100 transition hover:border-slate-600 disabled:opacity-50"
              >
                {taskBusy ? "Clearing..." : "Clear Data"}
              </button>
            </div>

            {taskMessage ? (
              <div className="mt-4 rounded border border-emerald-900/60 bg-emerald-950/30 p-3 text-sm text-emerald-200">
                <div>{taskMessage}</div>
                <Link href="/dashboard/tasks" className="mt-2 inline-flex font-medium text-emerald-100 underline underline-offset-4">
                  Open Goals &amp; Progress
                </Link>
              </div>
            ) : null}

            {predictResult && (
              <div className="mt-6 space-y-4">
                <div className="flex flex-col gap-3 sm:flex-row">
                  <button
                    disabled={aiBusy}
                    onClick={async () => {
                      setAiBusy(true);
                      try {
                        const res = await generateExplanation(payload);
                        setAiExplanation(res.explanation);
                      } catch (error) {
                        console.error("AI explanation failed:", error);
                      } finally {
                        setAiBusy(false);
                      }
                    }}
                    className="inline-flex items-center justify-center rounded bg-purple-500 px-4 py-3 text-sm font-semibold text-white transition hover:bg-purple-600 disabled:opacity-50"
                  >
                    {aiBusy ? "Generating..." : "AI Explanation"}
                  </button>
                  <button
                    disabled={aiBusy}
                    onClick={async () => {
                      setAiBusy(true);
                      try {
                        const res = await generateRecommendations(payload);
                        setAiRecommendations(res.recommendations);
                      } catch (error) {
                        console.error("AI recommendations failed:", error);
                      } finally {
                        setAiBusy(false);
                      }
                    }}
                    className="inline-flex items-center justify-center rounded bg-green-500 px-4 py-3 text-sm font-semibold text-white transition hover:bg-green-600 disabled:opacity-50"
                  >
                    {aiBusy ? "Generating..." : "AI Recommendations"}
                  </button>
                </div>

                {aiExplanation && (
                  <div className="rounded-lg border border-purple-700/40 bg-purple-950/20 p-4">
                    <div className="text-sm font-semibold text-purple-100 mb-2">AI Explanation</div>
                    <div className="text-sm text-purple-200">{aiExplanation}</div>
                  </div>
                )}

                {aiRecommendations && (
                  <div className="rounded-lg border border-green-700/40 bg-green-950/20 p-4">
                    <div className="text-sm font-semibold text-green-100 mb-2">AI Recommendations</div>
                    <div className="text-sm text-green-200 whitespace-pre-line">{aiRecommendations}</div>
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="space-y-6">
            <div className="rounded-lg border border-slate-800 bg-slate-900 p-5 text-slate-100 min-h-[500px]">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <div className="text-xl font-semibold">Risk Summary</div>
                  <div className="mt-1 text-base text-slate-300">Review your risk profile, preventive index, and suggested actions.</div>
                </div>
                {predictResult ? <div className="rounded-full bg-slate-950 px-4 py-2 text-base text-slate-300">Updated</div> : null}
              </div>
              {!predictResult ? (
                <div className="mt-6 text-base text-slate-300">Predict to unlock disease risk insight, forecast, and recommendations.</div>
              ) : (
                <>
                  <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
                    <RiskCard title="Overall Risk" value={`${Math.round(predictResult.overall_risk_score)}%`} level={predictResult.overall_risk_level} />
                    <RiskCard title="Health Index" value={Math.round(predictResult.health_index.score)} level={predictResult.health_category} />
                  </div>

                  <div className="mt-6 space-y-6">
                    <section className="rounded-3xl border border-emerald-700/40 bg-emerald-950/20 p-5">
                      <div className="flex items-center justify-between gap-3">
                        <div>
                          <div className="text-base font-semibold text-emerald-100">Metabolic Diseases</div>
                          <div className="mt-1 text-sm text-emerald-300">Diabetes, prediabetes, obesity, and metabolic syndrome risk.</div>
                        </div>
                        <span className="rounded-full bg-emerald-900 px-3 py-1 text-xs uppercase tracking-[0.18em] text-emerald-200">Green</span>
                      </div>
                      <div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2">
                        {groupedScores.metabolic.map((item: RiskScore) => (
                          <RiskCard
                            key={item.id}
                            title={item.name}
                            value={formatPct(item.probability)}
                            level={item.risk_level}
                            icon={iconMap[item.id]}
                          />
                        ))}
                      </div>
                    </section>

                    <section className="rounded-3xl border border-red-700/40 bg-red-950/20 p-5">
                      <div className="flex items-center justify-between gap-3">
                        <div>
                          <div className="text-base font-semibold text-red-100">Cardiovascular</div>
                          <div className="mt-1 text-sm text-red-300">Heart disease, hypertension, stroke, and overall cardiovascular risk.</div>
                        </div>
                        <span className="rounded-full bg-red-900 px-3 py-1 text-xs uppercase tracking-[0.18em] text-red-200">Red</span>
                      </div>
                      <div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2">
                        {groupedScores.cardiovascular.map((item: RiskScore) => (
                          <RiskCard
                            key={item.id}
                            title={item.name}
                            value={formatPct(item.probability)}
                            level={item.risk_level}
                            icon={iconMap[item.id]}
                          />
                        ))}
                      </div>
                    </section>

                    <section className="rounded-3xl border border-violet-700/40 bg-violet-950/20 p-5">
                      <div className="flex items-center justify-between gap-3">
                        <div>
                          <div className="text-base font-semibold text-violet-100">Other Risks</div>
                          <div className="mt-1 text-sm text-violet-300">Kidney disease, cholesterol disorder, lifestyle risk, and overall health.</div>
                        </div>
                        <span className="rounded-full bg-violet-900 px-3 py-1 text-xs uppercase tracking-[0.18em] text-violet-200">Purple</span>
                      </div>
                      <div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2">
                        {groupedScores.other.map((item: RiskScore) => (
                          <RiskCard
                            key={item.id}
                            title={item.name}
                            value={formatPct(item.probability)}
                            level={item.risk_level}
                            icon={iconMap[item.id]}
                          />
                        ))}
                        <RiskCard title="Overall Health Score" value={`${Math.round(predictResult.health_index.score)}`} level={predictResult.health_category} icon={ChartBarSquareIcon} />
                      </div>
                    </section>
                  </div>
                </>
              )}
            </div>

            {predictResult ? (
              <div className="rounded-lg border border-slate-800 bg-slate-900 p-5 text-slate-100">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <div className="text-lg font-semibold">Risk Forecast</div>
                    <div className="mt-1 text-sm text-slate-400">Projected risk trend for the next 6 months.</div>
                  </div>
                  <div className="rounded-full bg-slate-950 px-3 py-1 text-sm text-slate-300">Forecast</div>
                </div>
                <div className="mt-4 text-base">
                  <RiskTrendChart
                    title="Risk Progression"
                    data={(predictResult.risk_forecast || []).map((item: { months_ahead: number; diabetes_risk: number; heart_disease_risk: number; hypertension_risk: number }) => ({
                      x: `${item.months_ahead} mo`,
                      diabetes: item.diabetes_risk,
                      heart_disease: item.heart_disease_risk,
                      hypertension: item.hypertension_risk,
                    }))}
                    series={[
                      { dataKey: "diabetes", stroke: "#ef4444", label: "Diabetes" },
                      { dataKey: "heart_disease", stroke: "#f59e0b", label: "Heart Disease" },
                      { dataKey: "hypertension", stroke: "#10b981", label: "Hypertension" },
                    ]}
                    yFormatter={(v) => `${v}%`}
                  />
                </div>
              </div>
            ) : null}

            {predictResult ? (
              <div className="rounded-lg border border-slate-800 bg-slate-900 p-5 text-slate-100">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <div className="text-lg font-semibold">Dependency Explanations</div>
                    <div className="mt-1 text-sm text-slate-400">See why risks were adjusted and how conditions relate.</div>
                  </div>
                  <div className="rounded-full bg-slate-950 px-3 py-1 text-sm text-slate-300">Context-Aware</div>
                </div>
                <div className="mt-4 space-y-3 text-sm text-slate-300">
                  {(predictResult.dependency_explanations || []).map((message: string, idx: number) => (
                    <div key={idx} className="rounded border border-slate-800 bg-slate-950 p-3">{message}</div>
                  ))}
                  {!(predictResult.dependency_explanations?.length) ? (
                    <div className="text-slate-400">No dependency adjustments were needed for this profile.</div>
                  ) : null}
                </div>
              </div>
            ) : null}

            {predictResult ? (
              <div className="rounded-lg border border-slate-800 bg-slate-900 p-5 text-slate-100">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <div className="text-lg font-semibold">Explainable AI</div>
                    <div className="mt-1 text-sm text-slate-400">Understand the main feature drivers behind your prediction.</div>
                  </div>
                  <div className="rounded-full bg-slate-950 px-3 py-1 text-sm text-slate-300">SHAP</div>
                </div>
                <div className="mt-4">
                  <ExplainableChart explanations={predictResult.explanations} />
                </div>
              </div>
            ) : null}

            {predictResult ? (
              <div className="rounded-lg border border-slate-800 bg-slate-900 p-5 text-slate-100">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <div className="text-lg font-semibold">Recommendations</div>
                    <div className="mt-1 text-sm text-slate-400">Focused preventive actions based on your risk profile.</div>
                  </div>
                  <div className="rounded-full bg-slate-950 px-3 py-1 text-sm text-slate-300">Guidance</div>
                </div>
                <ul className="mt-4 grid gap-3 text-sm text-slate-300">
                  {(predictResult.recommendations || []).map((item: string, idx: number) => (
                    <li key={idx} className="rounded border border-slate-800 bg-slate-950 p-3">{item}</li>
                  ))}
                </ul>
              </div>
            ) : null}

            {predictResult?.anomalies?.anomaly_detected ? (
              <div className="rounded-lg border border-amber-600/60 bg-amber-950/30 p-5 text-amber-200">
                <div className="text-lg font-semibold">Alerts</div>
                <div className="mt-2 text-sm text-amber-100">Anomaly detection found unusual clinical or behavioral patterns.</div>
                <div className="mt-4 space-y-2 text-sm">
                  {(predictResult.anomalies.anomalies || []).map((message: string, idx: number) => (
                    <div key={idx} className="rounded border border-amber-700 bg-amber-950/50 p-3">{message}</div>
                  ))}
                </div>
              </div>
            ) : null}

            {predictResult ? (
              <div className="rounded-lg border border-slate-800 bg-slate-900 p-5 text-slate-100">
                <div className="text-lg font-semibold">Report & Confidence</div>
                <div className="mt-2 text-sm text-slate-400">Download a preventive report and share results with your care team.</div>
                <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center">
                  <button
                    onClick={async () => {
                      const blob = await downloadReport(predictResult?.prediction_id);
                      const url = window.URL.createObjectURL(blob);
                      const a = document.createElement("a");
                      a.href = url;
                      a.download = "preventive-health-report.pdf";
                      a.click();
                      window.URL.revokeObjectURL(url);
                    }}
                    className="rounded bg-emerald-500 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-600"
                  >
                    Download PDF Report
                  </button>
                  <div className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-2 text-sm text-slate-300">
                    Health index: <span className="font-semibold text-slate-100">{Math.round(predictResult.health_index.score)}</span>
                  </div>
                  <div className="rounded-lg border border-slate-700 bg-slate-950 px-4 py-2 text-sm text-slate-300">
                    Model confidence: <span className="font-semibold text-slate-100">{Math.round(predictResult.confidence?.overall ?? (predictResult.disease_scores?.diabetes?.confidence || 0))}%</span>
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </DashboardLayout>
    </RequireAuth>
  );
}
