import { addTask, createGoal, listGoals, updateGoal as patchGoal } from "./api";
import { HealthInput, PredictionResult, saveInput, saveLatestPrediction } from "./healthInput";

export const AUTO_GOAL_META_PREFIX = "AUTO_GOAL_META:";
export const AUTO_TASK_META_PREFIX = "AUTO_TASK_META:";
const SAFE_THRESHOLD = 30;
const SIGNIFICANT_CHANGE_THRESHOLD = 10;

type GoalMeta = {
  source: "prediction";
  goal_key: string;
  risk_type: string;
  risk_label: string;
  predicted_value: number;
  safe_threshold: number;
  prediction_id?: number;
  status?: "active" | "updated";
  last_updated_at?: string;
};

type TaskMeta = {
  source: "prediction_goal";
  goal_key: string;
  goal_id: number;
};

type GoalRecord = {
  id: number;
  created_at: string;
  goal_type: string;
  target_value: number;
  deadline?: string | null;
  status: string;
  progress_value: number;
  notes?: string | null;
};

function parseEmbeddedJson<T>(value: string | null | undefined, prefix: string): T | null {
  if (!value) return null;
  const line = value
    .split("\n")
    .map((item) => item.trim())
    .find((item) => item.startsWith(prefix));
  if (!line) return null;
  try {
    return JSON.parse(line.slice(prefix.length)) as T;
  } catch {
    return null;
  }
}

function toISODate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function buildPreventiveSchedule(taskCount: number, overallRiskScore: number): string[] {
  const today = new Date();
  const intensivePattern = [0, 1, 1, 2, 3, 3, 4, 5, 5];
  const steadyPattern = [0, 1, 2, 3, 4, 5, 6, 7, 8];
  const alternatePattern = [0, 2, 4, 6, 8, 10, 12, 14, 16];
  const offsets =
    overallRiskScore >= 66 ? intensivePattern : overallRiskScore >= 33 ? steadyPattern : alternatePattern;

  return Array.from({ length: taskCount }, (_, index) => {
    const date = new Date(today);
    date.setDate(today.getDate() + (offsets[index] ?? offsets[offsets.length - 1] + (index - offsets.length + 1) * 2));
    return toISODate(date);
  });
}

function buildGoalMeta(prediction: PredictionResult): GoalMeta {
  return {
    source: "prediction",
    goal_key: "overall-health-risk",
    risk_type: "overall_health_risk",
    risk_label: "overall health risk",
    predicted_value: Math.round(prediction.overall_risk_score),
    safe_threshold: SAFE_THRESHOLD,
    prediction_id: prediction.prediction_id,
  };
}

function buildGoalNotes(meta: GoalMeta) {
  return [
    `Reduce ${meta.risk_label} from ${meta.predicted_value}% to below ${meta.safe_threshold}%.`,
    "Auto-generated from the latest prediction workflow.",
    `${AUTO_GOAL_META_PREFIX}${JSON.stringify(meta)}`,
  ].join("\n");
}

function buildTaskNotes(goalId: number, meta: GoalMeta) {
  const taskMeta: TaskMeta = {
    source: "prediction_goal",
    goal_key: meta.goal_key,
    goal_id: goalId,
  };
  return [
    "Generated from prediction recommendations",
    `Linked goal: Reduce ${meta.risk_label} from ${meta.predicted_value}% to below ${meta.safe_threshold}%.`,
    `${AUTO_TASK_META_PREFIX}${JSON.stringify(taskMeta)}`,
  ].join("\n");
}

function parseGoalMeta(notes?: string | null) {
  return parseEmbeddedJson<GoalMeta>(notes, AUTO_GOAL_META_PREFIX);
}

export function parseTaskMeta(notes?: string | null) {
  return parseEmbeddedJson<TaskMeta>(notes, AUTO_TASK_META_PREFIX);
}

export function getGoalDisplayTitle(goal: GoalRecord) {
  const meta = parseGoalMeta(goal.notes);
  if (meta) {
    return `Reduce ${meta.risk_label} from ${meta.predicted_value}% to below ${meta.safe_threshold}%`;
  }
  const fallbackType = goal.goal_type.replace(/_/g, " ");
  return `Improve ${fallbackType} to ${goal.target_value}`;
}

export function isAutoPredictionGoal(goal: GoalRecord) {
  return Boolean(parseGoalMeta(goal.notes));
}

export function getGoalMeta(goal: GoalRecord) {
  return parseGoalMeta(goal.notes);
}

export async function clearAutoGeneratedGoals() {
  const goals = await listGoals();
  const items: GoalRecord[] = goals?.data || [];
  for (const goal of items) {
    if (!isAutoPredictionGoal(goal) || goal.status === "cancelled") {
      continue;
    }
    await patchGoal({ goal_id: goal.id, status: "cancelled" });
  }
}

function withGoalState(meta: GoalMeta, status: "active" | "updated"): GoalMeta {
  return {
    ...meta,
    status,
    last_updated_at: new Date().toISOString(),
  };
}

function findLatestAutoGoal(items: GoalRecord[], goalKey: string) {
  return items.find((goal) => {
    if (goal.status === "cancelled") return false;
    const goalMeta = parseGoalMeta(goal.notes);
    return goalMeta?.goal_key === goalKey;
  });
}

export function shouldUpdateGoal(previousPredictionValue: number, newPredictionValue: number) {
  return Math.abs(newPredictionValue - previousPredictionValue) > SIGNIFICANT_CHANGE_THRESHOLD;
}

export async function updateGoal(prediction: PredictionResult) {
  const meta = buildGoalMeta(prediction);
  const goals = await listGoals();
  const items: GoalRecord[] = goals?.data || [];
  const existing = findLatestAutoGoal(items, meta.goal_key);

  if (!existing) {
    return {
      action: "create" as const,
      goalId: null,
      goalTitle: `Reduce ${meta.risk_label} from ${meta.predicted_value}% to below ${meta.safe_threshold}%`,
      goalStatus: "active" as const,
      createdTaskCount: 0,
      scheduledDayCount: 0,
    };
  }

  const existingMeta = parseGoalMeta(existing.notes);
  if (!existingMeta) {
    return {
      action: "keep" as const,
      goalId: existing.id,
      goalTitle: getGoalDisplayTitle(existing),
      goalStatus: "active" as const,
      createdTaskCount: 0,
      scheduledDayCount: 0,
    };
  }

  if (!shouldUpdateGoal(existingMeta.predicted_value, meta.predicted_value)) {
    return {
      action: "keep" as const,
      goalId: existing.id,
      goalTitle: getGoalDisplayTitle(existing),
      goalStatus: existingMeta.status || "active",
      createdTaskCount: 0,
      scheduledDayCount: 0,
    };
  }

  const updatedMeta = withGoalState(meta, "updated");
  await patchGoal({
    goal_id: existing.id,
    status: "active",
    target_value: updatedMeta.safe_threshold,
    notes: buildGoalNotes(updatedMeta),
  });
  return {
    action: "update" as const,
    goalId: existing.id,
    goalTitle: `Reduce ${updatedMeta.risk_label} from ${updatedMeta.predicted_value}% to below ${updatedMeta.safe_threshold}%`,
    goalStatus: "updated" as const,
    createdTaskCount: 0,
    scheduledDayCount: 0,
  };
}

async function createAutoGoalAndTasks(prediction: PredictionResult) {
  const meta = withGoalState(buildGoalMeta(prediction), "active");
  const created = await createGoal({
    goal_type: meta.risk_type,
    target_value: meta.safe_threshold,
    notes: buildGoalNotes(meta),
  });
  const goalId = created?.data?.id;
  if (!goalId) {
    throw new Error("Failed to prepare the goal for this prediction.");
  }

  const recommendations = Array.from(
    new Set((prediction.recommendations || []).map((item) => item.trim()).filter(Boolean))
  ).slice(0, 6);
  const scheduleDates = buildPreventiveSchedule(recommendations.length, prediction.overall_risk_score);
  const taskNotes = buildTaskNotes(goalId, meta);

  for (const [index, recommendation] of recommendations.entries()) {
    await addTask({
      task_date: scheduleDates[index],
      title: recommendation,
      notes: taskNotes,
    });
  }

  return {
    action: "create" as const,
    goalId,
    goalTitle: `Reduce ${meta.risk_label} from ${meta.predicted_value}% to below ${meta.safe_threshold}%`,
    goalStatus: "active" as const,
    createdTaskCount: recommendations.length,
    scheduledDayCount: new Set(scheduleDates).size,
  };
}

export async function ensureAutoGoalAndTasks(prediction: PredictionResult) {
  const goalUpdate = await updateGoal(prediction);
  if (goalUpdate.action === "create") {
    return await createAutoGoalAndTasks(prediction);
  }
  return goalUpdate;
}

export async function applySimulation(
  userId: string | null,
  modifiedInput: HealthInput,
  simulatedResult: PredictionResult
) {
  saveInput(userId, modifiedInput);
  saveLatestPrediction(userId, simulatedResult);
  const goalUpdate = await ensureAutoGoalAndTasks(simulatedResult);
  return {
    ...goalUpdate,
    input: modifiedInput,
    prediction: simulatedResult,
  };
}
